# Generated by Django 5.0.6 on 2024-09-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0003_summary_sentiment_classification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
